language: python
cache:
  directories:
    - /tmp/docker-images
stages:
  - build
  - test
  - deploy
jobs:
  include:
    - stage: build
      services:
        - docker
      script:
        - set -e
        - docker build -t getslash/backslash:travis-${TRAVIS_COMMIT} -f docker/Dockerfile .
        - docker save -o /tmp/docker-images/image-travis-${TRAVIS_COMMIT} getslash/backslash:travis-${TRAVIS_COMMIT}
    - stage: test
      dist: xenial
      services:
        - docker
      script:
        - set -e
        - docker load -i /tmp/docker-images/image-travis-${TRAVIS_COMMIT}
        - docker tag getslash/backslash:travis-${TRAVIS_COMMIT} getslash/backslash:latest
        - docker-compose -f docker/docker-compose.yml run webapp pipenv run manage db upgrade
        - docker-compose -f docker/docker-compose.yml run webapp pipenv run pytest tests
