app_name: backslash

SECURITY_PASSWORD_HASH: sha512_crypt
# Change these settings to your own app credentials
SQLALCHEMY_TRACK_MODIFICATIONS: false

MAX_WARNINGS_PER_ENTITY: 50
MAX_QUERY_PAGE_SIZE: 2000

JSONIFY_PRETTYPRINT_REGULAR: false
JSON_SORT_KEYS: false

TRACEBACK_DIR: /opt/backslash/tracebacks

DEFAULT_PREFERENCES:
  time_format: "DD/MM/YYYY HH:mm:ss"
  start_page: 'default'

display_names:
  subject: subject
  related_entity: related

test_metadata_links: []

session_metadata_display_items: []

test_metadata_display_items: []
