[package]
name = "api-server"
version = "0.1.1"
authors = ["Rotem Yaari"]

[dependencies]
actix = "0.7.5"
actix-web = "0.7.13"
futures = "0.1.25"
url = "1.7.1"
log = "0.4.6"
env_logger = "0.5.13"
failure = "0.1.3"
structopt = "0.2"
sentry = "0.12.0"
sentry-actix = "0.12.0"
