version: '3'
services:

  webapp:
    image: getslash/backslash
    command: [
        "dockerize",
        "-timeout", "3600s",
        "-wait", "tcp://db:5432",
        "-wait", "tcp://rabbitmq:5672",
        ".env/bin/python", "manage.py", "docker-start"
        ]
    volumes:
      - "conf:/conf"
      - "uploads:/uploads"
    environment:
      - CONFIG_DIRECTORY=/conf
      - BACKSLASH_REDIS_SERVER=redis
      - BACKSLASH_DATABASE_URI=postgresql://backslash@db/backslash
      - BACKSLASH_TRACEBACKS_PATH=/uploads/tracebacks
      - BACKSLASH_CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
    depends_on:
      - db
      - redis
    logging:
      driver: journald

  worker:
    image: getslash/backslash
    command: dockerize -timeout 3600s -wait tcp://rabbitmq:5672 .env/bin/celery -A flask_app.tasks.main worker -B --loglevel=info --max-tasks-per-child=500
    logging:
      driver: journald
    environment:
      - CONFIG_DIRECTORY=/conf
      - BACKSLASH_REDIS_SERVER=redis
      - BACKSLASH_DATABASE_URI=postgresql://backslash@db/backslash
      - BACKSLASH_TRACEBACKS_PATH=/uploads/tracebacks
      - BACKSLASH_CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
    volumes:
      - "conf:/conf"
      - "uploads:/uploads"

  rabbitmq:
    image: rabbitmq

  db:
    image: "postgres:9.6"
    environment:
      - POSTGRES_USER=backslash
      - POSTGRES_DB=backslash
    volumes:
      - "db:/var/lib/postgresql/data"
  redis:
    image: "redis"

  monitor:
    image: "wrouesnel/postgres_exporter"
    environment:
      - DATA_SOURCE_NAME=postgresql://backslash@db:5432/backslash?sslmode=disable
    ports:
      - "9187:9187"
    depends_on:
      - db
    logging:
      driver: journald

  nginx:
    image: getslash/backslash
    volumes:
      - "conf:/conf"
      - "uploads:/uploads"
    environment:
      - BACKSLASH_HOSTNAME=
      - BACKSLASH_USE_SSL=
    command: ["dockerize",
              "-timeout", "3600s",
              "-wait", "http://webapp:8000",
              "-stdout", "/var/log/nginx/access.log", "-stderr", "/var/log/nginx/error.log",
              ".env/bin/python", "manage.py", "docker-nginx-start"]
    ports:
      - "8000:80"

volumes:
  uploads:
  conf:
  db:
