version: '3'
services:
  python-backend-api:
    image: getslash/backslash:unstable
  python-backend-ui:
    image: getslash/backslash:unstable
  api-server:
    image: getslash/backslash:unstable
  worker:
    image: getslash/backslash:unstable
  nginx:
    image: getslash/backslash:unstable
